// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package discount

import (
	"gorm.io/gorm"
	"iswift-go-project/internal/discount/delivery/http"
	discount2 "iswift-go-project/internal/discount/repository"
	discount3 "iswift-go-project/internal/discount/usecase"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *discount.DiscountHandler {
	discountRepository := discount2.NewDiscountRepository(db)
	discountUseCase := discount3.NewDiscountUseCase(discountRepository)
	discountHandler := discount.NewDiscountHandler(discountUseCase)
	return discountHandler
}
